line-length = 120
indent-width = 2
extend-include = ["*.ipynb"]
src = ["src"]

[lint]
select = ["E", "F", "B", "I"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
